import React, { useState } from 'react';
import '../styles/Dashboard.css';
import Header from '../components/Header'
import { FaArrowRightLong } from "react-icons/fa6";
import { AiFillGolden } from "react-icons/ai";
import { LuLayoutDashboard } from "react-icons/lu";




const Analytics = () => {
 
  const cardData = [
    { tittle: 'BAIP', body: 'Lorem Ipsum Dolor Sit Amet, Consectetur Ing Elit, Sed Do Eiusmod tempor Dunt Ut Labore Et Dolore Magna Aliqua. Ut Enim Ad Minin Veniam Ullamco Laboris.', icon: <AiFillGolden className="icon" /> },
    { tittle: 'Al Dashboard', body: 'AI Dashboard, short for Artificial Intelligence Dashboard, is a visual interface that provides real-time insights and analytics derived from artificial intelligence algorithms. It presents key performance indicators, trends, and predictions generated by AI models.', icon: <LuLayoutDashboard className="icon" /> },
  ]

  return (
    <div >
      <Header />
      <div className='conatiner-fluid w-100'>
        <div className='row w-100 h-100 p-4'>
          {cardData.map((item, i) => (
            <div className='col-12 col-md-6 col-lg-4 pl-4 mt-4' key={i}>
              <div key={i} className='card-custom'>
                <div className="card-header">
                  <span className='tittle-text'>{item.tittle}</span>
                  <span>{item.icon}</span>
                </div>
                <p className='pt-4'>{item.body}</p>
                <div className="card-footer">
                  <button className='button-arrow'>
                    <FaArrowRightLong className="logo-small" />
                  </button>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default Analytics;
